# Generated by Django 6.0.2 on 2026-03-03 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='status_limpeza',
            field=models.CharField(choices=[('L', 'Limpo'), ('N', 'Não limpo')], default='Não limpo', max_length=20),
        ),
    ]
